# Endercube-Plugin Configuration

# Command to be run when a player presses F
Fcommand:
  enabled: true
  commands:
    - 'say FCmd commmand 1'
    - 'say FCmd commmand 2'

# Kick a player when they join on a specific IP address
ipKick:
  enabled: true
  debugEnabled: false # Send the IP a player connected on in console whenever someone joins
  kickList: # These IP addresses include the port, normally :25565
    - 'your.domain.net:25565'
  kickMessage: 'Sorry, you can''t join on this ip address'


joinMessage:
  # Should the message only be sent once a player has accepted your resource pack
  resourcePack: true
  enabled: false
  # All support MiniMessage
  actions:
    broadcast: "<dark_gray><bold>[</bold><green>+<bold><dark_gray>]</bold> <white>%player_name%"
    title: "JoinMessage title"
    subtitle: "JoinMessage subtitle"
    actionbar: "JoinMessage actionbar"
    commands:
      - "say joinMessage commands"

quitMessage:
  enabled: false
  # All support MiniMessage
  actions:
    broadcast: "<dark_gray><bold>[</bold><red>-<bold><dark_gray>]</bold> <white>%player_name%"
    commands:
      - "say QuitMessage commands"