name: Endercube
version: '${project.version}'
main: me.zax71.Endercube.Endercube
api-version: 1.17
authors: [ Zax71 ]
description: Custom admin tools for Endercube
depend: [ PlaceholderAPI, PlayerWarps ]